//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSP2.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSP2.Desktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // Application Title
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        public static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        public static string App_DevVersion {
            get {
                return ResourceManager.GetString("App_DevVersion", resourceCulture);
            }
        }
        
        // Navigation Menu
        public static string Nav_ServerManagement {
            get {
                return ResourceManager.GetString("Nav_ServerManagement", resourceCulture);
            }
        }
        
        public static string Nav_LogConsole {
            get {
                return ResourceManager.GetString("Nav_LogConsole", resourceCulture);
            }
        }
        
        public static string Nav_PluginMarket {
            get {
                return ResourceManager.GetString("Nav_PluginMarket", resourceCulture);
            }
        }
        
        public static string Nav_DownloadManager {
            get {
                return ResourceManager.GetString("Nav_DownloadManager", resourceCulture);
            }
        }
        
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        public static string Nav_DebugConsole {
            get {
                return ResourceManager.GetString("Nav_DebugConsole", resourceCulture);
            }
        }
        
        // Status
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        public static string Status_CurrentPage {
            get {
                return ResourceManager.GetString("Status_CurrentPage", resourceCulture);
            }
        }
        
        public static string Status_ReadyText {
            get {
                return ResourceManager.GetString("Status_ReadyText", resourceCulture);
            }
        }
        
        // Server Management
        public static string ServerMgmt_Title {
            get {
                return ResourceManager.GetString("ServerMgmt_Title", resourceCulture);
            }
        }
        
        public static string ServerMgmt_Subtitle {
            get {
                return ResourceManager.GetString("ServerMgmt_Subtitle", resourceCulture);
            }
        }
        
        // ... (继续添加其他资源访问属性，但为了保持文件合理长度，实际使用时会自动生成)
    }
}

